[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
random_number_generator = "Cr1KAf6PqLd3zQA7WoYVnmkZfokvDQuL7hrZy3k7LH5b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
